version: '3.8'

services:
  db:
    image: postgres:15
    container_name: depthchart-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: depthchart
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres-init:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
      dockerfile: src/DepthChart.Api/Dockerfile
    container_name: depthchart-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=db;Database=depthchart;Username=postgres;Password=postgres
      - x-xpi-key=Dummy
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - db

volumes:
  pgdata:
